### ISSUE TITLE
Default behaviour should be in-line with black

### ISSUE THREAD

**Issue by FredHappyface** [jsh9/cercis#32]
**Is your feature request related to a problem? Please describe.**

Currently I wouldn't be able to adopt this easily as the current default behaviour differs significantly from black

**Describe the solution you'd like**

Please consider making the default behaviour in line with black and adding switches to change this. Eg. -t or --tabs changes indentation to use tabs

**Describe alternatives you've considered**

Using blackt 

**Additional context**

**Comment by jsh9** [comment]
Hi @FredHappyface , 

Please see the instructions [here](https://github.com/jsh9/cercis/blob/3d914350ad4c4aa48918b1eb31001ab4b9bcd9d5/README.md?plain=1#L715-L733) on how to completely fall back to `Black`'s behaviors.  You can tweak them however you'd like.

I would be very hesitant to make the default of `Cercis` completely identical to the default of `Black` though.  Because this means everyone who uses `Cercis` would at least need to tweak 1 config.

**Comment by jsh9** [comment]
(Closing this issue as "no need to fix".)
